cmake_minimum_required(VERSION 3.22)
if(NOT TEST_BINARY_DIR)
    message(FATAL_ERROR "Pass an empty TEST_BINARY_DIR for the profile checks.")
endif()
get_filename_component(source_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/source")
file(WRITE "${TEST_BINARY_DIR}/source/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.22)\nproject(ComposerProfileCheck NONE)\ninclude(\"${source_root}/buildscripts/cmake/PianomaniaComposer.cmake\")\nfile(WRITE \"\$\{CMAKE_BINARY_DIR\}/profile.txt\" \"\$\{PIANOMANIA_COMPOSER_PROFILE\}\")\n")

function(check_profile name profile mode should_succeed)
    set(args -DMUSE_APP_BUILD_MODE=${mode})
    if(NOT profile STREQUAL "default")
        list(APPEND args -DPIANOMANIA_COMPOSER_PROFILE=${profile})
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/source"
        -B "${TEST_BINARY_DIR}/${name}" ${args}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(should_succeed)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name} failed: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "Published Composer builds require|PIANOMANIA_COMPOSER_PROFILE must be")
        message(FATAL_ERROR "${name} did not reject the development release: ${output}${error}")
    endif()
endfunction()

check_profile(default-release default release TRUE)
file(READ "${TEST_BINARY_DIR}/default-release/profile.txt" default_profile)
if(NOT default_profile STREQUAL "production")
    message(FATAL_ERROR "Fresh builds must default to production")
endif()
check_profile(production-release production release TRUE)
check_profile(internal-release internal release FALSE)
check_profile(internal-testing internal testing FALSE)
check_profile(development-local development dev TRUE)
check_profile(development-release development release FALSE)
check_profile(development-testing development testing FALSE)

foreach(profile production development)
    set(PIANOMANIA_COMPOSER_PROFILE "${profile}")
    set(guard "${TEST_BINARY_DIR}/${profile}-package.cmake")
    configure_file("${source_root}/buildscripts/packaging/ComposerPackageGuard.cmake.in" "${guard}" @ONLY)
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${guard}"
        RESULT_VARIABLE result ERROR_VARIABLE error)
    if(profile STREQUAL "production" AND NOT result EQUAL 0)
        message(FATAL_ERROR "Production packaging was rejected: ${error}")
    elseif(NOT profile STREQUAL "production" AND (result EQUAL 0 OR NOT error MATCHES "Composer installers require"))
        message(FATAL_ERROR "${profile} packaging was not rejected: ${error}")
    endif()
endforeach()
message(STATUS "Composer profile checks passed: seven configurations and two packaging profiles")
